### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by yigoli** [DebolinaPaul/EWP#1]
Thanks for sharing your code. However, I am not sure how to run the code on my own. Could you provide a brief read_me for your work? Current read_me file is empty.

**Comment by DebolinaPaul** [comment]
Dear Yigoli,
Thank you for your interest in our paper. An example for the Entropy
Weighted Power k-Means code can be found in the Example run.ipynb file
(found here
<https://github.com/DebolinaPaul/EWP/blob/master/Example%20run.ipynb>). The
code is written in R, so you should first copy and paste it to a .R file in
R-Studio and run it like usual R codes. You should also be able to run the
ipynb file in Jupyter notebook directly.
Please feel free to email me if you have any further questions about the
code or the paper. Thank you again for your interest.

Thanks and Regards,
Debolina Paul
M.Stat 2nd Year
Indian Statistical Institute,
Kolkata, India.

**Comment by yigoli** [comment]
Thanks for your fast reply. 
I was able to run the code through notebooks in Kaggle, after I recognized that the language is R.
